name: Create and upload release assets

on:
  release:
    types:
      - created

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Determine tag name
        id: tagName
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Update manifest version
        uses: jossef/action-set-json-field@v1
        with:
          file: public/manifest.json
          field: Version
          value: ${{ steps.tagName.outputs.tag }}

      - name: NPM Install
        run: npm install

      - name: VUE Build
        run: npm run build

      - name: Create plugin folder structure
        run: cp -r ./dist de.perdoctus.streamdeck.homeassistant.sdPlugin

      - name: Zip Dist
        run: zip -r release.zip ./de.perdoctus.streamdeck.homeassistant.sdPlugin

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: de.perdoctus.streamdeck.homeassistant.streamDeckPlugin
          asset_content_type: application/zip
